openapi: 3.0.0
info:
  title: "SyncUs"
  version: "1.0.0"
  contact:
    name: Joshua Balsicas
    email: joshua@coolguyz.ca
    url: https://coolguyz.ca
servers:
  - url: https://comp3033-assignment2c.onrender.com/api
tags:
  - name: Georgian College
    description: The college that I am currently attending
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
paths:
  /syncs:
    get:
      security:
        - basicAuth: []
      description: Returns a list of SyncUs profiles
      responses:
        '200':
          description: Unfiltered list of SyncUs profiles
    post:
      security:
        - basicAuth: []
      description: Adds a new SyncUs profile
      responses:
        '200':
          description: Creates a new SyncUs profile
    put:
      security:
        - basicAuth: []
      description: Edits an existing SyncUs profile
      responses:
        '200':
          description: Allows changes to any existing SyncUs profile
    delete:
      security:
        - basicAuth: []
      description: Deletes an existing SyncUs profile
      responses:
        '200':
          description: Removes a SyncUs profile from the MongoDB database
        